name: Jest Tests
on:
  push:
    branches: [ main, master ] # push to main branch will trigger the workflow to test
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.12.3
        run_install: false
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run Jest tests
      run: pnpm test
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jest-results
        path: |
          apps/frontend/test-results/jest
          apps/frontend/test-results/coverage
        retention-days: 30